name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttest:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.1-focal
      env: 
        ADMIN_PASSWORD: ${{ secrets }}
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    - name: Run tests
      run: 
        echo "Start the shopping store application"
        chmod +x ./shopping-store-mac-amd64
        ./shopping-store-mac-amd64 &
        echo "√ènstall dependencies from lockfile"
        npm ci
        echo "Run playwright tests"
